### ISSUE TITLE
deploy in AWS us-west-2 failing, could not find AMI

### ISSUE THREAD

**Issue by asloan7** [EngineerBetter/control-tower#17]
Here's the error, where does this AMI live?:

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'ami-02e0c74167032a30b light':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"could not find AMI 'ami-02e0c74167032a30b'","ok_to_retry":false}

Exit code 1

**Comment by crsimmons** [comment]
Hi @asloan7 

The AMI is determined from the stemcell tarball [we pull from bosh deployment](https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/cpi.yml#L13). We haven't had a chance to try replicating this yet. What version of Control Tower are you trying to deploy with?

**Comment by asloan7** [comment]
Hi @crsimmons
I used Control Tower 0.4.0 https://github.com/EngineerBetter/control-tower/releases/tag/0.4.0
I see there is a 0.4.1 now...

**Comment by asloan7** [comment]
Newbie with these tools, should I cross-post the issue over at bosh-deployment?

**Comment by crsimmons** [comment]
Do you still get the same error with 0.4.1? What command are you using to deploy?

I just tried deploying with 0.4.1 and got:

```
➜  tmp  control-tower --version
Control-Tower version 0.4.1
➜  tmp  control-tower deploy --iaas aws --region us-west-2 name
...
  Creating VM for instance 'bosh/0' from stemcell 'ami-0c7a0659048cdcdf5 light'... Finished (00:00:40)
  Waiting for the agent on VM 'i-0642a332abd73cd50' to be ready... Finished (00:00:21)
  Creating disk... Finished (00:00:10)
...
```

**Comment by DanielJonesEB** [comment]
"Lite" stemcells (on AWS and GCP) are simply text files that contain the IDs of images that should already exist in given AWS regions. If they're not there, that's probably an issue with the stemcell's release engineering team.

You can [download the "lite" stemcell](https://s3.amazonaws.com/bosh-aws-light-stemcells/315.13/light-bosh-stemcell-315.13-aws-xen-hvm-ubuntu-xenial-go_agent.tgz) (linked to in the release notes), open it, and then seeing if the AMI exists in your given region.

Here's the contents:

```
---
name: bosh-aws-xen-hvm-ubuntu-xenial-go_agent
version: '315.13'
api_version: 2
bosh_protocol: '1'
sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
operating_system: ubuntu-xenial
stemcell_formats:
- aws-light
cloud_properties:
  infrastructure: aws
  ami:
    us-gov-west-1: ami-207e0d41
    ap-northeast-1: ami-027bfdc14fbdc212a
    ap-northeast-2: ami-04dea058bfbed4cca
    ap-south-1: ami-03208c7376d14e101
    ap-southeast-1: ami-06a172d75fff27b76
    ap-southeast-2: ami-0c7ed45c06cdf9a68
    ca-central-1: ami-005769a8f4600c073
    eu-central-1: ami-07a6b324ac19d7668
    eu-north-1: ami-0885555cfd5a5a8e2
    eu-west-1: ami-0b91c18f6cf2c40d6
    eu-west-2: ami-070cbbb8efcaa81e8
    eu-west-3: ami-0e0915a94edf9f04f
    sa-east-1: ami-0cbf282e2563b73d1
    us-east-1: ami-0de05f239db318556
    us-east-2: ami-072cdeeeca345be6f
    us-west-1: ami-0d57d1299b38fbfb0
    us-west-2: ami-09f796d5b23d4dee1
    cn-northwest-1: ami-086142c4fe2a3c07c
    cn-north-1: ami-06de86e363dd09cc6

```
