### ISSUE TITLE
self update job resets team permissions

### ISSUE THREAD

**Issue by RichardBradley** [EngineerBetter/control-tower#91]
I have GitHub auth federation set up and a "main" team in Concourse that looks like this:
```
roles:
- name: owner
  local:
    users: ["admin"]
- name: pipeline-operator
  github:
    teams: ["myorg:myteam"]
```

Every time I run the "self update" job, it resets all the permissions and I have to log in as the root admin user and re-apply my team's permissions with the yaml file.

I don't know if this is related to GitHub auth federation.

I feel like this is a bug and the self update should not change permissions.
